### ISSUE TITLE
does not mutate ternary operators correctly

### ISSUE THREAD

**Issue by brodybits** [stryker-mutator/stryker#2178]
**Summary**

While <https://github.com/stryker-mutator/stryker-handbook/blob/master/mutator-types.md#conditional-expression> leads me to believe that Stryker should mutate ternary operators, I think this kind of mutation is not really working for JavaScript or TypeScript, seems to be missing.

Here is a real-world example where it led to a missing test case on my software: <https://github.com/brodybits/create-react-native-module/issues/336>

The following update to the mutator specification seems to reproduce this issue:

```diff
diff --git a/packages/mutator-specification/src/ConditionalExpressionMutatorSpec.ts b/packages/mutator-specification/src/ConditionalExpressionMutatorSpec.ts
index 969ea28b..72913a8d 100644
--- a/packages/mutator-specification/src/ConditionalExpressionMutatorSpec.ts
+++ b/packages/mutator-specification/src/ConditionalExpressionMutatorSpec.ts
@@ -9,7 +9,7 @@ export default function ConditionalExpressionMutatorSpec(name: string, expectMut
     });
 
     it('should mutate ternary operator', () => {
-      expectMutation('a < 3? b : c', 'false? b : c', 'true? b : c');
+      expectMutation('a ? b : c', 'false ? b : c', 'true ? b : c');
     });
 
     it('should mutate < and >', () => {
```

I am not sure whether we should updating the existing mutator or add a new mutator that can pass this test update.

---

The rest of the information in this description is based on my real-world example in <https://github.com/brodybits/create-react-native-module/issues/336>:

> While starting to work on renaming the `className` option in the library API I discovered that this option is not really tested. In short, the following possible code mutation would not trigger any test failures:
> 
> ```diff
> diff --git a/lib/normalized-options.js b/lib/normalized-options.js
> index 82c48db..f90b946 100644
> --- a/lib/normalized-options.js
> +++ b/lib/normalized-options.js
> @@ -31,7 +31,7 @@ module.exports = (options) => {
>      moduleName
>        ? {}
>        : { moduleName: `${modulePrefix}-${paramCase(name)}` },
> -    className
> +    false
>        ? {}
>        : { className: `${prefix}${pascalCase(name)}` },
>      // namespace - library API member removed since Windows platform
> ```

I think we can see this here on Stryker dashboard, if we click to show killed mutations: <https://dashboard.stryker-mutator.io/reports/github.com/brodybits/create-react-native-module/master#lib/normalized-options.js>

**Stryker config**

For my real-world example: <https://github.com/brodybits/create-react-native-module/blob/master/stryker.conf.js>

```js
module.exports = config => {
  config.set({
    mutator: 'javascript',
    mutate: [
      // TBD there seems to be an issue with
      // Stryker mutation testing on
      // bin/*.js  (...)
      // 'bin/**/*.js',
      'lib/**/*.js',
      'templates/**/*.js',
      'unsupported-platforms/**/*.js'
    ],
    packageManager: 'yarn',
    reporters: [
      'html',
      'clear-text',
      'progress',
      'dashboard'
    ],
    testRunner: 'jest',
    transpilers: [],
    coverageAnalysis: 'off'
  });
};
```

**Test runner config**

none

**Stryker environment**

for the real-world example:

```
├─┬ @stryker-mutator/core@3.1.0
│ ├─┬ @stryker-mutator/api@3.1.0
│ ├── @stryker-mutator/util@3.1.0
├─┬ @stryker-mutator/javascript-mutator@3.1.0
│ ├── @stryker-mutator/api@3.1.0 deduped
├─┬ @stryker-mutator/jest-runner@3.1.0
│ ├── @stryker-mutator/api@3.1.0 deduped
```

for the real-world example:

```
% yarn why jest
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "jest"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "jest@26.0.1"
info Has been hoisted to "jest"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "48KB"
info Disk size with unique dependencies: "668KB"
info Disk size with transitive dependencies: "44.09MB"
info Number of shared dependencies: 92
✨  Done in 0.98s.
```

**Test runner environment**

for the real-world example:

```shell
npm run lint && npm run jest
```

removing the `npm run lint` part did not seem to have any effect

(no special Jest config file is used)

**Your Environment**

For my real-world example (I generally run Stryker in a cloud server which would be more powerful than my workstation):

| software         | version(s)
| ---------------- | -------
| node             |v12.16.3
| npm              |6.14.4
| Operating System |Ubuntu 20.04 LTS, Linux 5.4.0-26-generic

And here is [my GitHub action](https://github.com/brodybits/create-react-native-module/blob/master/.github/workflows/stryker.yml) which keeps the Stryker dashboard updated:

```yaml
# based on GitHub template:
name: Stryker CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - run: npm install

    # ref:
    # https://github.com/stryker-mutator/robobar-example/blob/master/.github/workflows/mutation-testing.yml
    - name: Run Stryker, with API key
      run: npm run stryker
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
```

**Add stryker.log**

from the real-world example:

[stryker.log](https://github.com/stryker-mutator/stryker/files/4588437/stryker.log)
